project:
  type: website
  output-dir: docs

website:
  title: "Linh Ngo"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "My work"
        href: blog.qmd
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/linhngo66/
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/thuy-linh-ngo/
      - icon: envelope
        href: mailto:linhngo66@gmail.com
format:
  html:
    theme: litera
    css: styles.css